const properties = [
    { name: "GO", price: 0, rent: 0 },
    { name: "Med Ave", price: 60, rent: 2 },
    { name: "Chest", price: 0, rent: 0 },
    { name: "Baltic", price: 60, rent: 4 },
    { name: "Tax", price: 0, rent: 0 },
    { name: "Reading RR", price: 200, rent: 25 },
    { name: "Oriental", price: 100, rent: 6 },
    { name: "Chance", price: 0, rent: 0 },
    { name: "Vermont", price: 100, rent: 6 },
    { name: "Conn Ave", price: 120, rent: 8 },
    { name: "Jail", price: 0, rent: 0 },
    { name: "St. Charles", price: 140, rent: 10 },
    { name: "Elec Co.", price: 150, rent: 0 },
    { name: "States", price: 140, rent: 10 },
    { name: "Virginia", price: 160, rent: 12 },
    { name: "Penn RR", price: 200, rent: 25 },
    { name: "St. James", price: 180, rent: 14 },
    { name: "Chest", price: 0, rent: 0 },
    { name: "Tenn Ave", price: 180, rent: 14 },
    { name: "NY Ave", price: 200, rent: 16 },
    { name: "Free Park", price: 0, rent: 0 },
    { name: "Kentucky", price: 220, rent: 18 },
    { name: "Chance", price: 0, rent: 0 },
    { name: "Indiana", price: 220, rent: 18 },
    { name: "Illinois", price: 240, rent: 20 },
    { name: "B&O RR", price: 200, rent: 25 },
    { name: "Atlantic", price: 260, rent: 22 },
    { name: "Ventnor", price: 260, rent: 22 },
    { name: "Water", price: 150, rent: 0 },
    { name: "Marvin", price: 280, rent: 24 },
    { name: "Go to Jail", price: 0, rent: 0 },
    { name: "Pacific", price: 300, rent: 26 },
    { name: "NC Ave", price: 300, rent: 26 },
    { name: "Chest", price: 0, rent: 0 },
    { name: "Penn Ave", price: 320, rent: 28 },
    { name: "Short Line", price: 200, rent: 25 },
    { name: "Chance", price: 0, rent: 0 },
    { name: "Park Place", price: 350, rent: 35 },
    { name: "Luxury Tax", price: 0, rent: 0 },
    { name: "Boardwalk", price: 400, rent: 50 }
];
