const properties = {
    0: { name: "GO", price: 0, owner: null },
    1: { name: "Mediterranean Avenue", price: 60, owner: null },
    2: { name: "Community Chest", price: 0, owner: null },
    3: { name: "Baltic Avenue", price: 60, owner: null },
    4: { name: "Income Tax", price: 0, owner: null },
    5: { name: "Reading Railroad", price: 200, owner: null },
    6: { name: "Oriental Avenue", price: 100, owner: null },
    7: { name: "Chance", price: 0, owner: null },
    8: { name: "Vermont Avenue", price: 100, owner: null },
    9: { name: "Connecticut Avenue", price: 120, owner: null },
    19: { name: "St. Charles Place", price: 140, owner: null },
    29: { name: "Electric Company", price: 150, owner: null },
    39: { name: "States Avenue", price: 140, owner: null },
    49: { name: "Virginia Avenue", price: 160, owner: null },
    59: { name: "Pennsylvania Railroad", price: 200, owner: null },
    69: { name: "St. James Place", price: 180, owner: null },
    79: { name: "Community Chest", price: 0, owner: null },
    89: { name: "Tennessee Avenue", price: 180, owner: null },
    99: { name: "New York Avenue", price: 200, owner: null },
    98: { name: "Free Parking", price: 0, owner: null },
    97: { name: "Kentucky Avenue", price: 220, owner: null },
    96: { name: "Chance", price: 0, owner: null },
    95: { name: "Indiana Avenue", price: 220, owner: null },
    94: { name: "Illinois Avenue", price: 240, owner: null },
    93: { name: "B&O Railroad", price: 200, owner: null },
    92: { name: "Atlantic Avenue", price: 260, owner: null },
    91: { name: "Ventnor Avenue", price: 260, owner: null },
    90: { name: "Water Works", price: 150, owner: null },
    80: { name: "Marvin Gardens", price: 280, owner: null },
    70: { name: "Go to Jail", price: 0, owner: null },
    60: { name: "Pacific Avenue", price: 300, owner: null },
    50: { name: "North Carolina Avenue", price: 300, owner: null },
    40: { name: "Community Chest", price: 0, owner: null },
    30: { name: "Pennsylvania Avenue", price: 320, owner: null },
    20: { name: "Short Line Railroad", price: 200, owner: null },
    10: { name: "Chance", price: 0, owner: null }
};

function loadProperties() {
    console.log("Properties loaded.");
}
